
services:
  training:
    build:
      context: ..
      dockerfile: docker/Dockerfile.training
    container_name: training
    env_file: .env.training
    volumes:
      - ${O_DRIVE_PATH}:/mnt/O:rw # dataset access
      - ${TOOLS_LIB_PATH}:/workspace/tools:ro # access to tools library
      - ../train.py:/workspace/train.py:ro # training script
      - ../configs:/workspace/configs:ro # config files
      - ../src:/workspace/src:ro # source code
      - ../logs:/workspace/logs:rw # tensorboard logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - mlflow