services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    image: image_classifier_api
    container_name: image_classifier_api
    env_file: .env.api
    ports:
      - "8000:8000"
    environment:
      - API_MODEL_NAME
      - API_RUN_NAME
      - API_DEVICE
      - API_TRACKING_URI
      - API_EXPERIMENT_NAME
    volumes:
      - ${O_DRIVE_PATH}:/mnt/O:rw
    restart: unless-stopped
    depends_on:
      - mlflow
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]