data:
  channels:
  - 1
  - 2
  - 3
  - 4
  - 5
  crop_size: 224
  root_dir: O:\BTSData\MeasurementData\MIG\MIG-Exp03-CP-40X-bin1X1_20230831_143904\MIG-Exp03-CP-40X-bin1X1
dataloader:
  batch_size: 64
  cache_size: 32
  exclude_wells:
  - - MIG-Exp03-CP-40X-bin1X1
    - K07
  - - MIG-Exp03-CP-40X-bin1X1
    - K08
  - - MIG-Exp03-CP-40X-bin1X1
    - K09
  max_samples_per_label: 4
  max_wells_per_label: 2
  num_workers: 0
  pin_memory: true
  tile_stride: null
  train_val_split: 0.5
  use_mongodb: true
  use_tiling: true
  verbose: true
model:
  base_channels: 32
  channel_multiplier: 2
  dropout: 0.5
  hidden_dim: 128
  name: SimpleCNN
  num_blocks: 4
training:
  learning_rate: 0.0001
  max_epochs: 100
  optimizer:
    type: AdamW
  scheduler:
    factor: 0.5
    mode: min
    patience: 5
    type: ReduceLROnPlateau
  weight_decay: 0.0001
