checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: checkpoints
  filename: "cnn-{epoch:02d}-{val_acc:.4f}"
  monitor: "val/acc"
  mode: max
  save_top_k: 1
  save_last: true

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  enabled: false
  monitor: "val/loss"
  patience: 10
  mode: min
